import { Inter, Roboto_Mono, Edu_NSW_ACT_Foundation } from "next/font/google";
import Banner from "@/components/Banner";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Copyright from "@/components/Copyright";
import Cart from "@/components/Cart";
import "./globals.css";
import MyContextProvider from "@/context/Provider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
const inter = Inter({ subsets: ["latin"] });

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  display: "swap",
});
const edu_nsw = Edu_NSW_ACT_Foundation({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  display: "swap",
});

export const metadata = {
  title: "MegaSalesPK",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${edu_nsw.variable} ${roboto_mono.variable}`}
      >
        <MyContextProvider>
          <Navbar />
          <AntdRegistry>{children}</AntdRegistry>
          <Footer />
          <Copyright />
        </MyContextProvider>
      </body>
    </html>
  );
}
