import { Inter } from "next/font/google";
import Banner from "@/components/Banner";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Copyright from "@/components/Copyright";
import Cart from "@/components/Cart";
import "./globals.css";
import MyContextProvider from "@/context/Provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IKKhazana",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MyContextProvider>
          <Navbar />
          {children}
          <Footer />
          <Copyright />
        </MyContextProvider>
      </body>
    </html>
  );
}
